feat: added a container health check step after deploying containers.

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -385,6 +385,38 @@ jobs:
 
                                           echo "Containers deployed...\n\n"
                                           echo "----------------------------------------------"
+                        
+
+                        - name: Verify all containers are healthy
+                          uses: appleboy/ssh-action@v0.1.10
+                          with:
+                                  host: ${{ secrets.TARGET_HOST }}
+                                  username: ${{ secrets.TARGET_USER }}
+                                  key: ${{ secrets.SSH_PRIVATE_KEY }}
+                                  port: ${{ secrets.TARGET_PORT }}
+
+                                  proxy_host: ${{ secrets.GATEWAY_HOST }}
+                                  proxy_port: ${{ secrets.GATEWAY_PORT }}
+                                  proxy_username: ${{ secrets.GATEWAY_USER }}
+                                  proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
+                                  script: |
+                                        set -euo pipefail
+                                        echo "----------------------------------------------"
+                                        echo "Waiting for containers to settle..."
+                                        sleep 10
+                                        echo "Waited."
+
+                                        docker ps -a
+                                        BAD=$(docker ps -a --filter "status=exited" --filter "health=unhealthy" --format "{{.Names}} {{.Status}}")
+
+                                        if [ -n "$BAD" ]; then
+                                                echo "❌ Containers failed:"
+                                                echo "$BAD"
+                                                exit 1
+                                        fi
+
+                                        echo "✅ All containers healthy"
+
 
                         - name: Install and run system metric daemon (collectd)
                           uses: appleboy/ssh-action@v0.1.10
